### ISSUE TITLE
[FEAT] Support for "Desktop Virtualization User" role assignment

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-avd#3]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Unless there are reasons not to, it would be good if the module takes user(s) or group(s) as (optional) input variable and assigns the roles in scope of the application group.

From https://learn.microsoft.com/en-us/azure/developer/terraform/configure-avd-rbac

```hcl
data "azurerm_role_definition" "role" { # access an existing built-in role
  name = "Desktop Virtualization User"
}

resource "azurerm_role_assignment" "role" {
  scope              = azurerm_virtual_desktop_application_group.dag.id
  role_definition_id = data.azurerm_role_definition.role.id
  principal_id       = azuread_group.aad_group.id
}
```

which was also suggested in https://github.com/hashicorp/terraform-provider-azurerm/issues/14146#issuecomment-971444726

It would allow to complete the AVD configuration using the module.

### New or Affected Resource(s)/Data Source(s)

azurerm_role_assignment

**Comment by zfiel** [comment]
Hello @mloskot ,

Thank you for opening this issue. We will look into it.

**Comment by zfiel** [comment]
Hello @mloskot ,

Apologies for the delay.

Your suggestion is available in https://github.com/claranet/terraform-azurerm-avd/tree/v7.3.0. Thanks for the idea.

**Comment by mloskot** [comment]
Hi @zfiel That's awesome, thank you very much! I will test it out soon.

I'm closing this issue as completed then.
