### ISSUE TITLE
[FEAT] Upgrade hashicorp/azuread to 3.0

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-avd#4]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Could this dependency be updated to `>~ 3.0` ?
https://github.com/claranet/terraform-azurerm-avd/blob/950798fccd04fd598466a4b95c3b1390f553fa43/versions.tf#L10-L11

It looks like only data sources are referenced from the hashicorp/azuread provider, so this upgrade should be fairly safe, not blocked by any breaking changes.

### New or Affected Resource(s)/Data Source(s)

hashicorp/azuread

**Comment by Shr3ps** [comment]
Hello thanks again for your issue @mloskot !

We have multiple modules interacting each others with AzureAD provider, we will probably bump to v3 in all of them with the v8 breaking version of our modules.

For this module (avd), maybe we can change the constrain with >= 2

**Comment by mloskot** [comment]
Thanks @Shr3ps, yes, it would be helpful if the constraint changed to the 2.x as [minimum allowed versions (...) allowing the user of the module flexibility to upgrade to newer versions](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#best-practices).

**Comment by mloskot** [comment]
Thank you so much @Shr3ps! I meant to open PR, got caught in between team calls and you beat me :)
